version: '3'
services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "15432:5432"
    volumes:
      - ./postgres-bd:/var/lib/postgresql/data 
  mysql:
    image: mysql:5.7.20
    volumes:
      - ./mysql-data:/var/lib/mysql      
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  apache-php:
    image: 'php:8.0-apache'
    container_name: php
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
     - '80:80'
    volumes:
     - ./html:/var/www/html 
    depends_on:
      - mysql
      - postgres

    # backend:
    #   image: node:latest
    #   working_dir: /app
    #   volumes:
    #     - "./backend:/app"
    #   command: ["node", "./server.js"]
    #   expose:
    #     - "8000"
      

    # teste-apache:
    #   image: 'php:7.1.3-fpm'
    #   container_name: php
    #   restart: always
    #   ports:
    #   - '80:80'
    #   volumes:
    #   - ./html:/var/www/html 
    #   depends_on:
    #     - teste-mysql


  # docker run -it php:8.0-apache bash
  # docker system prune
  # docker inspect <id_do_container> | grep "IPAddress"




